Issue 369 - Substituiçao do Dicionario de Dados
AlertaDengue/AlertaDengue pull request #444
Opened 2021-07-07 23:07 UTC by Breno-Azevedo

Fiz as substituições no dicionário de dados pelo conteúdo do arquivo .txt anexado

2021-07-08 09:45 UTC, esloch requested changes
Here you have uploaded a file that doesn't need to be in the repository, move it outside the project structure.

2021-07-15 12:47 UTC, Breno-Azevedo reviewed
Excluí o arquivo que eu havia enviado por engano e acrescentei a versão em inglês do dicionário de dados.

2021-07-15 13:53 UTC, esloch commented
> Excluí o arquivo que eu havia enviado por engano e acrescentei a versão em inglês do dicionário de dados.

Para as traduções no Django recomendo a leitura da documentação:
https://docs.djangoproject.com/en/3.2/topics/i18n/translation/
https://docs.djangoproject.com/en/3.2/ref/django-admin/#django-admin-makemessages

2021-07-16 16:35 UTC, Breno-Azevedo commented
Ficou assim após as modificações.
![Captura de tela de 2021-07-15 22-46-24](https://user-images.githubusercontent.com/84725504/125980150-4064ffdf-9d9e-47ed-8d2b-7b802584d5b6.png)

2021-07-16 16:52 UTC, esloch approved these changes

2021-07-16 21:07 UTC, esloch commented
Muito bom @Breno-Azevedo!
Agora para resolver os conflitos faz falta um ***pull rebase***  (pegar e ordenar os últimos commits) em seu repositório local, e um novo push para o remote.

2021-07-21 09:31 UTC, merged