Allow upload of dbfs at national level
AlertaDengue/AlertaDengue pull request #455
Opened 2021-08-28 00:13 UTC by esloch

- Resolves #452.

2021-08-30 08:36 UTC, esloch commented
Changed *U.F* label to *Abrangência*:

![chik_se33_form_20210830](https://user-images.githubusercontent.com/3450741/131308940-ff05d312-1fb9-41ed-bff6-0f2b5563895e.png)
--- 
Inserted *BR-Brasil* for selection in *ABBREVIATION_CODE_CHOICES*
```
ABBREVIATION_CODE_CHOICES = (
    ('BR', 'Brasil'),
    (None, '-----'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
...
```
--- 
Table dbf_dbf result:

![table_dbf_dbf_upload_20210830](https://user-images.githubusercontent.com/3450741/131310112-17676c03-141d-46d7-8c26-41500c6705ba.png)

@fccoelho do you think? Change the column name from *state_abbreviation* to *abbreviation_code_choices*?

```
infodengue> \d dbf_dbf
+--------------------+--------------------------+-------------------------------------------------------+
| Column             | Type                     | Modifiers                                             |
|--------------------+--------------------------+-------------------------------------------------------|
| id                 | integer                  |  not null default nextval('dbf_dbf_id_seq'::regclass) |
| file               | character varying(100)   |  not null                                             |
| uploaded_at        | timestamp with time zone |  not null                                             |
| export_date        | date                     |  not null                                             |
| notification_year  | integer                  |  not null                                             |
| uploaded_by_id     | integer                  |  not null                                             |
| state_abbreviation | character varying(2)     |                                                       |
| municipio          | character varying(255)   |  not null                                             |
+--------------------+--------------------------+-------------------------------------------------------+
```

2021-08-30 20:31 UTC, fccoelho commented
@esloch, let's keep it simple and just call it `abbreviation`

2021-08-30 20:34 UTC, fccoelho requested changes
just change the column name.

2021-08-30 20:34 UTC, fccoelho commented on AlertaDengue/dbf/forms.py
> +        choices=DBF.ABBREVIATION_CODE_CHOICES, label=_("Abrangência")
call it just `abbreviation`

2021-09-01 11:59 UTC, esloch commented
> just change the column name.

```
infodengue> \d dbf_dbf
+-------------------+--------------------------+-------------------------------------------------------+
| Column            | Type                     | Modifiers                                             |
|-------------------+--------------------------+-------------------------------------------------------|
| id                | integer                  |  not null default nextval('dbf_dbf_id_seq'::regclass) |
| file              | character varying(100)   |  not null                                             |
| uploaded_at       | timestamp with time zone |  not null                                             |
| export_date       | date                     |  not null                                             |
| notification_year | integer                  |  not null                                             |
| uploaded_by_id    | integer                  |  not null                                             |
| abbreviation      | character varying(2)     |                                                       |
| municipio         | character varying(255)   |  not null                                             |
+-------------------+--------------------------+-------------------------------------------------------+

```


> just change the column name.

Done!
```
infodengue> \d dbf_dbf
+-------------------+--------------------------+-------------------------------------------------------+
| Column            | Type                     | Modifiers                                             |
|-------------------+--------------------------+-------------------------------------------------------|
| id                | integer                  |  not null default nextval('dbf_dbf_id_seq'::regclass) |
| file              | character varying(100)   |  not null                                             |
| uploaded_at       | timestamp with time zone |  not null                                             |
| export_date       | date                     |  not null                                             |
| notification_year | integer                  |  not null                                             |
| uploaded_by_id    | integer                  |  not null                                             |
| abbreviation      | character varying(2)     |                                                       |
| municipio         | character varying(255)   |  not null                                             |
+-------------------+--------------------------+-------------------------------------------------------+

```

2021-09-01 12:02 UTC, esloch commented
> @esloch, let's keep it simple and just call it `abbreviation`  

Done!
```
class DBF(models.Model):
    ABBREVIATION = (
        ('BR', 'Brasil'),
        (None, '-----'),
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
 ```

2021-09-01 15:49 UTC, esloch commented
> just change the column name.

Used the *migrations.RenameField* according to [this tip](https://gist.github.com/dhbradshaw/e2bdeb502b0d0d2acced)

2021-09-01 16:24 UTC, esloch commented
@fccoelho I did some tests on _staging, NGINX is giving connection timeout error when uploading dbf:
```
2021/09/01 12:19:56 [error] 54402#54402: *1114270 upstream prematurely closed connection while reading response  
header from upstream, client: 179.190.120.154, server: infostaging.dengue.mat.br, request:   
"POST /dbf/upload/ HTTP/1.1", upstream: "http://127.0.0.1:8080/dbf/upload/",   
host: "infostaging.dengue.mat.br", referrer: "https://infostaging.dengue.mat.br/dbf/upload/"

179.190.120.154 - - [01/Sep/2021:12:19:56 -0300] "GET /favicon.ico HTTP/1.1"   
404 3303 "https://infostaging.dengue.mat.br/dbf/upload/" "Mozilla/5.0 (X11; Linux x86_64)   
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
``` 
I will do some tests in nginx on the server: 
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

2021-09-01 17:58 UTC, fccoelho commented
maybe this can help:
https://serverfault.com/questions/414987/nginx-proxy-timeout-while-uploading-big-files

2021-09-01 18:01 UTC, esloch commented
> maybe this can help:
> https://serverfault.com/questions/414987/nginx-proxy-timeout-while-uploading-big-files

Thanks!

2021-09-02 18:04 UTC, esloch commented
@fccoelho I modified NGINX like this:
```
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout      1200;
        proxy_send_timeout         1200;
        proxy_read_timeout         1200;
        send_timeout               1200;
        client_max_body_size       10m;
        client_body_buffer_size    128k;        
    }
  ```
and gunicorn timeout to::
  ```
  ad_main.wsgi:application --timeout 1200
  ``` 
I got this result:
  ```
  ...Instanciando SINAN (/MEDIA_ROOT/BR-DEN-2021-08-24-2021_BqKjgjs.dbf, 2021)
.....Task dbf.tasks.import_dbf_to_database[21e0cd70-be3c-44ee-94c8-7a969d086b73] raised unexpected: MemoryError((784130, 123), dtype('O'))
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/deploy/AlertaDengue/dbf/tasks.py", line 75, in import_dbf_to_database
    sinan = Sinan(dbf.file.path, dbf.notification_year)
  File "/srv/deploy/AlertaDengue/dbf/sinan.py", line 86, in __init__
    self.tabela = pd.DataFrame(self.dbf.records)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 509, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 526, in to_arrays
    return _list_of_dict_to_arrays(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 645, in _list_of_dict_to_arrays
    content = list(lib.dicts_to_array(data, list(columns)).T)
  File "pandas/_libs/lib.pyx", line 379, in pandas._libs.lib.dicts_to_array
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 736. MiB for an array with shape (784130, 123) and data type object
  ```
  Here, we came across what we had said about in the meeting...

2021-09-02 18:19 UTC, fccoelho commented
Memory issue. Like we discussed, we have to change the code to read from the DBF in chunks.

2021-09-15 01:03 UTC, esloch commented
@fccoelho we will have to open a issue to change from dbfread to geopandas in the other functions :)
profiling: 
![Screenshot_20210914_205823](https://user-images.githubusercontent.com/3450741/133353055-70c58c2a-9cfd-4144-80aa-e4bb20a55e57.png)

2021-09-15 06:33 UTC, fccoelho commented
Why geopandas and not just pandas?

2021-09-15 07:27 UTC, esloch commented
> Why geopandas and not just pandas?  

*import geopandas as gpd...*  

What do you think if we pass that on in the views?
https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dbf/views.py#L40-L41

I'm going to create utils module for dbf:
``` 
def chunk_gen(chunksize, totalsize):
    chunks = totalsize//chunksize

    for i in range(chunks):
        yield i * chunksize, (i + 1) * chunksize
    
    rest = totalsize % chunksize
    
    if rest:
        yield (
            chunks * chunksize, 
            (chunks * chunksize) + rest
        )

def chunk_dbf_filter(dbfname):
    dbf = Dbf5(dbfname)
    for chunk, (lowerbound, upperbound) in enumerate(
        chunk_gen(1000, dbf.numrec)
    ):
        df = gpd.read_file(
            dbfname, rows=slice(lowerbound, upperbound)
        )
        df[field_map.values()].to_parquet(f"./DBFS/data/BR_ZIKA_SE30_2021/data-{chunk}.parquet")
```

2021-09-16 22:27 UTC, esloch commented
TypeError:
```
  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dbf/sinan.py", line 192, in save_to_pgsql
    row[13] = None if not row[13] else int(row[13])  # nu_idade_n
  File "pandas/_libs/missing.pyx", line 360, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
``` 
##### Solved with:

>row[13] = (
  >                  None if pd.isnull(row[13]) else int(row[13])
    >            )
```  File "/work_lab/fiocruz/repositories/AlertaDengue/AlertaDengue/dbf/sinan.py", line 198, in save_to_pgsql
    cursor.execute(insert_sql, row)
  File "/docker-env/miniconda/envs/alertadengue/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.ProgrammingError: can't adapt type 'NAType'
``` 
##### Solved with add new rule:
>row[6] = (
>    None if pd.isnull(row[6]) else str(row[6])
>)
##### Some fields have null values:
``` 

(Pdb) p row
DT_NOTIFIC    2021-07-01
SEM_NOT               26
NU_ANO              2021
DT_SIN_PRI    2021-06-29
SEM_PRI               26
DT_DIGITA     2021-07-05
NM_BAIRRO           <NA>
ID_BAIRRO           None
ID_MUNICIP       2612505
NU_NOTIFIC       3931606
ID_AGRAVO          A92.0
DT_NASC       2021-04-04
CS_SEXO                M
NU_IDADE_N          <NA>

(Pdb) p row.isna()
DT_NOTIFIC    False
SEM_NOT       False
NU_ANO        False
DT_SIN_PRI    False
SEM_PRI       False
DT_DIGITA     False
NM_BAIRRO      True
ID_BAIRRO      True
ID_MUNICIP    False
NU_NOTIFIC    False
ID_AGRAVO     False
DT_NASC       False
CS_SEXO       False
NU_IDADE_N     True

2021-09-20 20:06 UTC, fccoelho approved these changes

2021-09-20 22:14 UTC, merged