Refactore containers
AlertaDengue/AlertaDengue pull request #599
Opened 2023-01-27 19:39 UTC by esloch

2023-02-06 23:37 UTC, xmnlab requested changes
The targets on makim should be fixed and added two notes ... it is a good progress!!

2023-02-06 23:37 UTC, xmnlab commented on conda/dev.yaml
> -  - nodefaults
You probably should keep nodefaults to avoid mixing packages from anaconda and conda forge

2023-02-06 23:37 UTC, xmnlab commented on conda/dev.yaml
> +    - containers-sugar >=1.1.0
```suggestion
    - containers-sugar >=1.2.0
```

2023-02-07 22:20 UTC, fccoelho approved these changes

2023-02-08 14:47 UTC, xmnlab commented
is it already working here?

2023-02-08 15:43 UTC, esloch commented
I don't know why the wait don't exit to tmate.

2023-02-13 15:06 UTC, merged