feat(upload-sinan): include CSV option to upload-sinan command
AlertaDengue/AlertaDengue pull request #710
Opened 2024-03-18 20:09 UTC by luabida

Recognize CSV files in upload-sinan command

2024-03-19 10:44 UTC, fccoelho approved these changes

2024-03-25 18:18 UTC, fccoelho requested changes

2024-03-25 18:18 UTC, fccoelho commented on AlertaDengue/upload/models.py
> +            "RESIDUE_{filename} and it requires further human verification"
Replace "residue" by "misparsed". Look for other places where it occurs, and replace as well.

2024-03-25 18:18 UTC, fccoelho commented on AlertaDengue/upload/models.py
> +            "moved errored rows to `error_residue` file. "
change this line to:  "moved rows that failed parsing to `error_misparsed` file. "

2024-03-25 18:18 UTC, fccoelho commented on AlertaDengue/upload/sinan/validations.py
> +                f"Residue file name {fpath.name} doesn't start with RESIDUE_"
should be: f"Misparsed file name... MISPARSED_"

2024-05-03 18:42 UTC, luabida commented
merging it to test in staging, the PR does not affect any other app

2024-05-03 18:42 UTC, merged